spring:
  application:
    name: merchant-business-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtUser
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  one-time-expiration: 30000
  secret: VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAyNTYtYml0IHNlY3VyaXR5IQ==
  expiration: 86400000

#logging:
#  level:
#    org.springframework.web: DEBUG
#    com.nchl: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  file:
#    name: logs/application.log

server:
  error:
    include-stacktrace: always


aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  sns:
    topic:
      arn: arn:aws:sns:us-east-1:532877842082:global