spring:
  application:
    name: merchant-business-gateway
  datasource:
    url: jdbc:postgresql://10.250.3.31:5432/Creditor
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  one-time-expiration: 30000
  secret: VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCAyNTYtYml0IHNlY3VyaXR5IQ==
  expiration: 86400000

#logging:
#  level:
#    org.springframework.web: DEBUG
#    com.nchl: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  file:
#    name: logs/application.log

server:
  error:
    include-stacktrace: always
